# -*- mode: org -*-
# -*- coding: utf-8 -*-
#+TITLE: A Random Forests python Implementation - Machine Learning Course
#+AUTHOR: Valéria S. Girelli
#+LATEX_HEADER: \usepackage[margin=2cm,a4paper]{geometry}
#+STARTUP: overview indent
#+TAGS: noexport(n) deprecated(d)
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+SEQ_TODO: TODO(t!) STARTED(s!) WAITING(w!) | DONE(d!) CANCELLED(c!) DEFERRED(f!)

* Random Forests

This repository holds a Random Forests implementation in python,
applying the ensemble learning method and stratified
cross-validation. This implementation works for both numerical and
categorical attributes. The work is part of the Machine Learning
course on the Informatics Institute at UFRGS. 

The objective is to provide an original implementation and analyze the
impact that some parameters have on the model performance. More
specifically, we aim to optimize the number of trees on the ensemble
method. 

* Required libraries
You might need to install some libraries on your system:
#+BEGIN_SRC 
pip3 install pandas
pip3 install numpy
#+END_SRC

* Usage and input files
To run the application you must inform the input file that contains
the dataset and an additional file containing the type (numerical or
categorical) of each attribute: 
#+BEGIN_SRC 
python3 main.py <file_name> <separator> <attribute_type_file> <separator> <target> <ntrees> <max_depth>

if you're using \t as a file separator, you need to pass in the following way: $'\t'
#+END_SRC

The file containing the attributes types must be a csv file and
must present a row for each attribute and its type in the following
manner: 
#+BEGIN_SRC 
<attribute_1> | <attribute_2> 
  <cat>       |    <num> 
#+END_SRC
